version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    restart: on-failure
    depends_on:
      - datab
    environment:
      MYSQL_HOST: datab
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: tfs_db
      MYSQL_PORT: 3302
    volumes:
      - ./back:/app
    command: npm run dev -- --port 3000 --host 0.0.0.0
    ports:
      - 3332:3000
    networks:
      - tfs_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: on-failure
    volumes:
      - ./front:/app
    command: npm run dev -- --port 4000 --host 0.0.0.0
    ports:
      - 1212:4000
    networks:
      - tfs_network

  datab:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tfs_db
    ports:
      - 3302:3306
    networks:
      - tfs_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - datab
    environment:
      PMA_HOST: datab
      PMA_ARBITRARY: 1
    restart: always
    ports:
      - 2111:80
    links: 
      - datab
    networks:
      - tfs_network

networks:
    tfs_network:

